# Site settings
title: login.gov
description: Usability testing
baseurl: ""

include: ['_pages']

# Build settings
markdown: kramdown
sass:
  style: compressed

exclude:
  - node_modules
  - manifest.yml
  - vendor
